### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by edvilme**
Updated site to reflect look of hackclub.com :P

### CODE REVIEW

**Comment by edvilme** [comment]
Close #2

**Comment by edvilme** [comment]
.

**Comment by MatthewStanciu** [comment]
Hey wow I'm sorry we never saw this until just now. This looks great, but could you add a section that's either a call to action for starting a club or a section directing people to the full site in English? Then I can merge. Also the button for Slack doesn't work for me.

(FYI: I downloaded the files from your latest build and [uploaded them to Netlify](https://eloquent-minsky-3c821a.netlify.app) so that I could see what it looks like)

**Comment by lachlanjc** [comment]
Yikes, my changing the branch closed this forcibly. Could you reopen a new PR to replace this? It should auto-deploy now.

**Pull request closed without merging**
